[2020-12-04 07:35:00,914] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/customer_db Caused by :No suitable driver") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/customer_db Caused by :No suitable driver")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:567)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/customer_db Caused by :No suitable driver")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at kanishka.db_connector.0_1_0.db_connector.$kanishka_db_connector_0_1_0__init_0(db_connector:20)
	at kanishka.db_connector.0_1_0.db_connector.$kanishka_db_connector_0_1_0__testinit_(db_connector:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-12-04 07:42:23,990] SEVERE {b7a.log.crash} - error("Invalid JDBC URL: <JDBC url /+ DB name>") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Invalid JDBC URL: <JDBC url /+ DB name>")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:567)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Invalid JDBC URL: <JDBC url /+ DB name>")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:41)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at kanishka.db_connector.0_1_1.db_connector.$kanishka_db_connector_0_1_1__init_0(db_connector:20)
	at kanishka.db_connector.0_1_1.db_connector.$kanishka_db_connector_0_1_1__testinit_(db_connector:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
